#!/usr/bin/env python3
"""Generate the repo README from the flake itself plus a curated highlight file.

The split is deliberate:

  * Facts that drift  — hosts, module lists, flake inputs, script counts, and
    each module's one-line summary — are read out of the tree at generation
    time. They cannot go stale, because nothing hand-maintains them.
  * Prose that needs a human — the framing, the highlight write-ups — lives in
    showcase.toml. Every highlight names the module paths it is describing, and
    generation FAILS if one of those paths no longer exists. A renamed module
    breaks the build instead of quietly leaving a lie in the README.

Module summaries are harvested from the leading comment block of each .nix file,
which in this repo is usually the best documentation that exists. Blocks that
are actually commented-out Nix code are detected and skipped rather than
printed as if they were prose.

Usage:
    gen_readme.py            rewrite README.md between the showcase markers
    gen_readme.py --check    exit 1 if the README is out of date (no writes)
    gen_readme.py --stdout   print the generated block, write nothing
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

BEGIN = "<!-- showcase:begin — generated by docs/showcase/showcase.sh, do not edit by hand -->"
END = "<!-- showcase:end -->"

SCRIPT_DIR = Path(__file__).resolve().parent
CONFIG_ROOT = SCRIPT_DIR.parent.parent


# ── module summaries ─────────────────────────────────────────────────────────

# A comment line is "code-like" if it looks like Nix that someone commented out
# rather than a sentence someone wrote for a reader.
CODE_HINTS = (
    re.compile(r"^[A-Za-z_][\w.\-]*\s*="),      # attr = value
    re.compile(r"[;{}]\s*$"),                    # statement / block punctuation
    re.compile(r"^\s*[\[\]}{]"),                 # bare brackets
    re.compile(r"^\+\+"),                        # list concat
    re.compile(r"^(imports|pkgs|inputs|config|lib)\b[.\s]"),
    re.compile(r"^\w+\s*\("),                    # function application
)


def looks_like_code(line: str) -> bool:
    line = line.strip()
    if not line:
        return False
    return any(p.search(line) for p in CODE_HINTS)


@dataclass
class Module:
    path: str            # repo-relative, e.g. modules/core/focus-dns.nix
    name: str            # focus-dns
    summary: str         # one line, may be ""
    detail: str          # remaining prose, may be ""

    @property
    def documented(self) -> bool:
        return bool(self.summary)


# The end of a Nix module's argument header: `{pkgs, ...}: {`, `{pkgs, ...}: let`,
# or the same closing a multi-line argument set.
HEADER_END = re.compile(r"\}\s*:\s*(\{|let)?\s*$")

# Decoration used to draw section rules inside comments.
DECOR = "─│┌┐└┘━-=*#"


def _run_from(lines: list[str], start: int) -> list[str]:
    block: list[str] = []
    for line in lines[start:]:
        stripped = line.strip()
        if stripped.startswith("#"):
            block.append(stripped.lstrip("#").strip())
        else:
            break
    return block


def extract_comment_block(text: str, max_scan: int = 60) -> list[str]:
    """Return the module's docstring: the comment block at the top of the file.

    Only two positions count as a docstring — the very first line, or the first
    line after the module's argument header. A comment anywhere else is
    describing the line of Nix beneath it, not the module, and lifting it into
    the README produces summaries like "Add user to libvirtd group" for a file
    that does far more than that.
    """
    lines = text.splitlines()[:max_scan]

    i = 0
    while i < len(lines) and not lines[i].strip():
        i += 1
    if i >= len(lines):
        return []

    if lines[i].strip().startswith("#"):
        return _run_from(lines, i)

    for j, line in enumerate(lines):
        if HEADER_END.search(line):
            k = j + 1
            while k < len(lines) and not lines[k].strip():
                k += 1
            if k < len(lines) and lines[k].strip().startswith("#"):
                return _run_from(lines, k)
            return []
    return []


def summarize(path: Path, repo_rel: str) -> Module:
    name = path.stem
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return Module(repo_rel, name, "", "")

    block = extract_comment_block(text)
    # Drop trailing blanks; keep interior ones as paragraph breaks.
    while block and not block[-1]:
        block.pop()
    while block and not block[0]:
        block.pop(0)

    if not block:
        return Module(repo_rel, name, "", "")

    # A `#!${pkgs.bash}/bin/bash` heredoc shebang is not documentation.
    if block[0].startswith("!"):
        return Module(repo_rel, name, "", "")

    real = [ln for ln in block if ln]
    if not real:
        return Module(repo_rel, name, "", "")
    # A lone comment line sitting in docstring position is almost always
    # annotating the statement below it ("# Add user to libvirtd group"), not
    # describing the module. Real docstrings here run to several lines.
    if len(real) < 2:
        return Module(repo_rel, name, "", "")
    if sum(looks_like_code(ln) for ln in real) / len(real) >= 0.4:
        return Module(repo_rel, name, "", "")

    # A comment that just restates the filename carries nothing.
    if len(real) == 1 and real[0].rstrip(".").lower() in {name, f"{name}.nix"}:
        return Module(repo_rel, name, "", "")

    # The first paragraph is the summary; anything after it is detail.
    first_para: list[str] = []
    for ln in block:
        if not ln:
            break
        first_para.append(ln)
    summary = " ".join(first_para).strip()

    # Trim to one sentence if the paragraph runs long, but keep short
    # multi-clause summaries whole.
    if len(summary) > 200:
        # Split on a sentence end, but not on "e.g." / "i.e." / an initial —
        # a summary that stops at "Android-only apps (e.g." reads as truncated.
        m = re.search(r"(?<![A-Z])(?<!\be\.g)(?<!\bi\.e)(?<!\betc)[.!?]\s+(?=[A-Z(])",
                      summary[:260])
        if m:
            summary = summary[: m.start() + 1]
        else:
            summary = summary[:200].rsplit(" ", 1)[0] + "…"
    # Section-rule decoration reads as noise in a table cell.
    summary = summary.strip(DECOR + " ")
    summary = re.sub(r"[─━]{2,}", " ", summary)
    summary = re.sub(r"\s+", " ", summary).strip(DECOR + " ")
    if len(summary) < 12:
        return Module(repo_rel, name, "", "")

    rest = block[len(first_para) :]
    detail = "\n".join(rest).strip()
    return Module(repo_rel, name, summary, detail)


def collect_modules(subdir: str) -> list[Module]:
    base = CONFIG_ROOT / subdir
    if not base.is_dir():
        return []
    mods = []
    for p in sorted(base.glob("*.nix")):
        if p.name in {"default.nix", "default.desktop.nix"}:
            continue
        mods.append(summarize(p, f"{subdir}/{p.name}"))
    return mods


# ── other facts read from the tree ───────────────────────────────────────────

def read_hosts() -> list[str]:
    base = CONFIG_ROOT / "hosts"
    if not base.is_dir():
        return []
    return sorted(p.name for p in base.iterdir() if p.is_dir())


def read_flake_inputs() -> list[tuple[str, str]]:
    """(name, source) for every top-level flake input, from flake.lock."""
    lock = CONFIG_ROOT / "flake.lock"
    if not lock.is_file():
        return []
    try:
        data = json.loads(lock.read_text())
    except (OSError, json.JSONDecodeError):
        return []
    nodes = data.get("nodes", {})
    root = nodes.get(data.get("root", "root"), {}).get("inputs", {})
    out = []
    for name, ref in sorted(root.items()):
        if isinstance(ref, list):
            ref = ref[0] if ref else None
        node = nodes.get(ref, {})
        orig = node.get("original", {})
        if orig.get("type") == "github":
            src = f"{orig.get('owner')}/{orig.get('repo')}"
            if orig.get("ref"):
                src += f" @ {orig['ref']}"
        elif orig.get("type") == "path":
            # Never print the absolute path — these are local working copies and
            # the README is public.
            src = "local path"
        elif orig.get("url"):
            src = orig["url"]
        else:
            src = orig.get("type", "")
        out.append((name, src))
    return out


def count_scripts() -> int:
    base = CONFIG_ROOT / "modules/home/scripts/scripts"
    if not base.is_dir():
        return 0
    return sum(1 for p in base.iterdir() if p.is_file() or p.is_dir())


def count_units() -> int:
    """Rough count of systemd units this config declares."""
    pat = re.compile(r"systemd\.(user\.)?(services|timers)\.")
    seen = 0
    for p in CONFIG_ROOT.rglob("modules/**/*.nix"):
        try:
            seen += len(pat.findall(p.read_text(encoding="utf-8", errors="replace")))
        except OSError:
            pass
    return seen


def read_manifest() -> list[dict]:
    mf = SCRIPT_DIR / "screenshots" / "manifest.json"
    if not mf.is_file():
        return []
    try:
        return json.loads(mf.read_text())
    except (OSError, json.JSONDecodeError):
        return []


def read_showcase() -> dict:
    f = SCRIPT_DIR / "showcase.toml"
    if not f.is_file():
        sys.exit(f"missing {f}")
    with f.open("rb") as fh:
        return tomllib.load(fh)


# ── rendering ────────────────────────────────────────────────────────────────

def md_escape(s: str) -> str:
    return s.replace("|", "\\|")


def render(cfg: dict, mods_core: list[Module], mods_home: list[Module]) -> str:
    meta = cfg.get("meta", {})
    highlights = cfg.get("highlight", [])
    shots = {s["id"]: s for s in read_manifest()}
    hosts = read_hosts()
    inputs = read_flake_inputs()
    all_mods = mods_core + mods_home

    o: list[str] = [BEGIN, ""]
    o.append(f"# {meta.get('title', 'NixOS configuration')}")
    o.append("")
    if meta.get("tagline"):
        o.append(f"> {meta['tagline']}")
        o.append("")

    stats = [
        f"**{len(hosts)}** hosts",
        f"**{len(all_mods)}** modules",
        f"**{count_units()}** systemd units",
        f"**{count_scripts()}** scripts",
        f"**{len(inputs)}** flake inputs",
    ]
    o.append(" · ".join(stats))
    o.append("")

    if meta.get("intro"):
        o.append(meta["intro"].strip())
        o.append("")

    # Hero shot, if one has been captured.
    hero = meta.get("hero")
    if hero and hero in shots:
        s = shots[hero]
        o.append(f"![{s['title']}](docs/showcase/{s['file']})")
        o.append("")
        if s.get("caption"):
            o.append(f"<sub>{s['caption']}</sub>")
            o.append("")

    # Highlights.
    if highlights:
        o.append("## What's actually in here")
        o.append("")
        for h in highlights:
            o.append(f"### {h['title']}")
            o.append("")
            o.append(h["body"].strip())
            o.append("")
            shot_id = h.get("shot")
            if shot_id and shot_id in shots:
                s = shots[shot_id]
                o.append(f"![{s['title']}](docs/showcase/{s['file']})")
                o.append("")
            srcs = h.get("modules", [])
            if srcs:
                links = ", ".join(f"[`{m}`]({m})" for m in srcs)
                o.append(f"<sub>Source: {links}</sub>")
                o.append("")

    # Remaining screenshots that no highlight claimed.
    claimed = {h.get("shot") for h in highlights} | {hero}
    gallery = [s for sid, s in sorted(shots.items()) if sid not in claimed]
    if gallery:
        o.append("## More screenshots")
        o.append("")
        for s in gallery:
            o.append(f"**{s['title']}**")
            o.append("")
            o.append(f"![{s['title']}](docs/showcase/{s['file']})")
            o.append("")
            if s.get("caption"):
                o.append(f"<sub>{s['caption']}</sub>")
                o.append("")

    # Hosts.
    if hosts:
        o.append("## Hosts")
        o.append("")
        host_notes = meta.get("hosts", {})
        o.append("| Host | Role |")
        o.append("| --- | --- |")
        for h in hosts:
            o.append(f"| `{h}` | {md_escape(host_notes.get(h, '—'))} |")
        o.append("")
        primary = meta.get("primary_host", hosts[0])
        o.append("```sh")
        o.append(f"sudo nixos-rebuild switch --flake .#{primary}")
        o.append("```")
        o.append("")

    # Full module inventory.
    o.append("## Every module")
    o.append("")
    o.append(
        "Summaries below are lifted straight from each module's own leading "
        "comment, so they cannot drift from the code."
    )
    o.append("")
    for label, mods, path in (
        ("System — `modules/core`", mods_core, "modules/core"),
        ("Home — `modules/home`", mods_home, "modules/home"),
    ):
        documented = [m for m in mods if m.documented]
        bare = [m for m in mods if not m.documented]
        o.append("<details>")
        o.append(
            f"<summary><b>{label}</b> — {len(mods)} modules, "
            f"{len(documented)} with a written rationale</summary>"
        )
        o.append("")
        if documented:
            o.append("| Module | What it does |")
            o.append("| --- | --- |")
            for m in documented:
                o.append(f"| [`{m.name}`]({m.path}) | {md_escape(m.summary)} |")
            o.append("")
        if bare:
            o.append(
                "*No module-level comment yet — these do their job without "
                "explaining themselves:* "
                + ", ".join(f"[`{m.name}`]({m.path})" for m in bare)
            )
            o.append("")
        o.append("</details>")
        o.append("")

    # Flake inputs.
    if inputs:
        o.append("## Flake inputs")
        o.append("")
        o.append("<details>")
        o.append(f"<summary>{len(inputs)} pinned inputs</summary>")
        o.append("")
        o.append("| Input | Source |")
        o.append("| --- | --- |")
        for name, src in inputs:
            o.append(f"| `{name}` | {md_escape(src)} |")
        o.append("")
        o.append("</details>")
        o.append("")

    if meta.get("outro"):
        o.append(meta["outro"].strip())
        o.append("")

    o.append(END)
    return "\n".join(o).rstrip() + "\n"


def validate(cfg: dict) -> list[str]:
    """Every module path a highlight names must exist. Loudly."""
    problems = []
    for h in cfg.get("highlight", []):
        for m in h.get("modules", []):
            if not (CONFIG_ROOT / m).exists():
                problems.append(f"highlight {h.get('id', h.get('title'))!r} -> missing {m}")
    hero = cfg.get("meta", {}).get("hero")
    ids = {s["id"] for s in read_manifest()}
    if hero and ids and hero not in ids:
        problems.append(f"meta.hero {hero!r} has no captured screenshot")
    return problems


def splice(readme: Path, block: str) -> str:
    if readme.is_file():
        old = readme.read_text(encoding="utf-8")
    else:
        old = ""
    if BEGIN in old and END in old:
        head = old.split(BEGIN)[0]
        tail = old.split(END, 1)[1]
        return head + block.rstrip("\n") + tail
    # First run: generated block on top, whatever was there kept underneath.
    return block + ("\n" + old.lstrip("\n") if old.strip() else "")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if out of date")
    ap.add_argument("--stdout", action="store_true", help="print, do not write")
    args = ap.parse_args()

    cfg = read_showcase()
    problems = validate(cfg)
    if problems:
        for p in problems:
            print(f"error: {p}", file=sys.stderr)
        print(
            "\nshowcase.toml references things that no longer exist. "
            "Fix the paths (or the README will describe code you deleted).",
            file=sys.stderr,
        )
        return 2

    mods_core = collect_modules("modules/core")
    mods_home = collect_modules("modules/home")
    block = render(cfg, mods_core, mods_home)

    if args.stdout:
        sys.stdout.write(block)
        return 0

    readme = CONFIG_ROOT / cfg.get("meta", {}).get("readme", "README.md")
    new = splice(readme, block)

    if args.check:
        current = readme.read_text(encoding="utf-8") if readme.is_file() else ""
        if current != new:
            print(f"{readme} is out of date — run docs/showcase/showcase.sh readme", file=sys.stderr)
            return 1
        print(f"{readme} is up to date")
        return 0

    readme.write_text(new, encoding="utf-8")

    undoc = [m for m in mods_core + mods_home if not m.documented]
    print(f"wrote {readme}")
    print(
        f"  {len(mods_core) + len(mods_home)} modules, "
        f"{len(undoc)} without a leading comment"
    )
    if undoc:
        print("  undocumented: " + ", ".join(m.name for m in undoc[:12])
              + (" …" if len(undoc) > 12 else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
