# AeroSpace — the tiling window manager that replaces Hyprland.
#
# The full keymap and the reasoning behind the Super→Option substitution live in
# the generated TOML below. The short version: Command is load-bearing on macOS,
# so Option becomes the window-manager modifier, and every Hyprland binding
# keeps its letter.
#
# AeroSpace itself is a cask (nikitabobko/tap/aerospace, see
# modules/darwin/homebrew.nix) — it needs Accessibility permission, which a
# Nix-built unsigned binary cannot hold.
_: {
  home.file.".aerospace.toml".text = ''
    # AeroSpace — the Hyprland replacement.
    #
    # THE ONE SUBSTITUTION THAT MAKES THIS WORK: on Linux the window-manager
    # modifier is Super. On macOS Command is load-bearing (Cmd+C/V/W/Q/Tab are
    # system-wide and cannot be reclaimed without breaking every app), so OPTION
    # takes the Super role. kitty is told `macos_option_as_alt yes` so Option still
    # reaches tmux/nvim as Meta inside the terminal.
    #
    # Generated by modules/home/darwin/aerospace.nix — DO NOT EDIT ~/.aerospace.toml
    # by hand, it is overwritten on every switch.

    # Config-version 2 is the current highest. The only behavioural change from 1:
    # persistent-workspaces is no longer inferred from the key bindings, so it is
    # listed explicitly below to keep workspaces 1-20 alive when empty.
    config-version = 2

    after-login-command = []
    after-startup-command = [
      # JankyBorders draws the focused-window border AeroSpace itself does not.
      # Mauve #cba6f7 is the Catppuccin accent used everywhere else in this config;
      # width 4 so the focused tile reads at a glance with gaps 0 (the laptop had
      # a 2px Hyprland border, but Retina + no gaps wants more).
      # borders is single-instance: this call re-configures the brew-services one.
      'exec-and-forget /opt/homebrew/bin/borders style=round width=4.0 hidpi=on active_color=0xffcba6f7 inactive_color=0xff45475a',
    ]

    start-at-login = true
    enable-normalization-flatten-containers = true
    enable-normalization-opposite-orientation-for-nested-containers = true

    # Hyprland ran dwindle with 0 gaps. Same here.
    accordion-padding = 0

    default-root-container-layout = 'tiles'
    default-root-container-orientation = 'auto'

    # Follow focus between AeroSpace and macOS's own notion of the active window.
    on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
    automatically-unhide-macos-hidden-apps = true

    # SketchyBar redraws its workspace strip on every switch; FOCUSED_WORKSPACE
    # rides along in the environment so the plugin does not have to ask again.
    exec-on-workspace-change = ['/bin/bash', '-c',
      '/opt/homebrew/bin/sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
    ]

    # Keep every bound workspace alive even when empty (config-version = 2 makes
    # this explicit instead of inferring it from the bindings).
    persistent-workspaces = [
      '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
      '11', '12', '13', '14', '15', '16', '17', '18', '19', '20',
    ]

    [key-mapping]
    preset = 'qwerty'

    [gaps]
    inner.horizontal = 0
    inner.vertical = 0
    outer.left = 0
    outer.bottom = 0
    outer.top = 0
    outer.right = 0

    [mode.main.binding]

    # ── focus / move / resize ──────────────────────────────────────────────────
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-shift-left = 'resize width -50'
    alt-shift-right = 'resize width +50'
    alt-shift-up = 'resize height -50'
    alt-shift-down = 'resize height +50'

    # ── workspaces 1-10 and 11-20 ──────────────────────────────────────────────
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'
    alt-0 = 'workspace 10'
    alt-ctrl-1 = 'workspace 11'
    alt-ctrl-2 = 'workspace 12'
    alt-ctrl-3 = 'workspace 13'
    alt-ctrl-4 = 'workspace 14'
    alt-ctrl-5 = 'workspace 15'
    alt-ctrl-6 = 'workspace 16'
    alt-ctrl-7 = 'workspace 17'
    alt-ctrl-8 = 'workspace 18'
    alt-ctrl-9 = 'workspace 19'
    alt-ctrl-0 = 'workspace 20'

    # move the focused window to a workspace (1-10)
    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'
    alt-shift-0 = 'move-node-to-workspace 10'

    alt-tab = 'workspace-back-and-forth'

    # ── window control ─────────────────────────────────────────────────────────
    alt-q = 'close'
    alt-f = 'fullscreen'
    alt-space = 'layout floating tiling'
    alt-s = 'layout tiles horizontal vertical'

    # ── launchers ──────────────────────────────────────────────────────────────
    # Super+T on Linux was `kitty -e tmux -L hypr new-session`; keep the socket name
    # so tmux-sessionizer and the M-n binding attach to the same server.
    alt-t = 'exec-and-forget open -na kitty --args -e tmux -L hypr new-session'
    alt-shift-t = ['layout floating', 'exec-and-forget open -na kitty']
    alt-b = 'exec-and-forget open -a "Zen"'

    # Raycast takes Vicinae's slot (alt-d), plus emoji and clipboard history on the
    # same letters they had under Hyprland. These are raycast:// deeplinks rather
    # than key synthesis so they work whatever Raycast's own hotkeys are set to.
    alt-d = 'exec-and-forget open -a Raycast'
    alt-e = 'exec-and-forget open -g "raycast://extensions/raycast/emoji-symbols/search-emoji-symbols"'
    alt-v = 'exec-and-forget open -g "raycast://extensions/raycast/clipboard-history/clipboard-history"'
    alt-x = 'exec-and-forget password-picker'

    # ── Super+Alt+<letter> app hotkeys, ×19 ────────────────────────────────────
    # On Linux these were Super+Alt+<letter>. Here Option already plays the role of
    # Super, so the second modifier is Ctrl: alt-ctrl-<letter>. `open -a` is
    # focus-or-launch natively, which is exactly what focus_app.sh emulated.
    alt-ctrl-c = 'exec-and-forget open -a "Google Calendar"'  # Google Calendar
    alt-ctrl-a = 'exec-and-forget open -a "Anki"'  # Anki
    alt-ctrl-o = 'exec-and-forget open -a "Obsidian"'  # Obsidian
    alt-ctrl-p = 'exec-and-forget open -a "PrusaSlicer"'  # PrusaSlicer
    alt-ctrl-k = 'exec-and-forget open -a "Slack"'  # Slack
    alt-ctrl-d = 'exec-and-forget open -a "Discord"'  # Discord
    alt-ctrl-m = 'exec-and-forget open -a "Superhuman"'  # Superhuman
    alt-ctrl-g = 'exec-and-forget open -a "GIMP"'  # GIMP
    alt-ctrl-e = 'exec-and-forget open -a "Finder"'  # Finder
    alt-ctrl-i = 'exec-and-forget open -a "WhatsApp"'  # WhatsApp
    alt-ctrl-y = 'exec-and-forget open -a "Gemini"'  # Gemini
    alt-ctrl-u = 'exec-and-forget open -a "UltiMaker Cura"'  # Cura
    alt-ctrl-h = 'exec-and-forget open -a "Beeper"'  # Beeper
    alt-ctrl-s = 'exec-and-forget open -a "Spotify"'  # Spotify
    alt-ctrl-t = 'exec-and-forget open -a "Tasker"'  # tasker
    alt-ctrl-l = 'exec-and-forget open -a "Linear"'  # Linear
    alt-ctrl-w = 'exec-and-forget open -a "Wispr Flow"'  # Wispr Flow
    alt-ctrl-r = 'exec-and-forget open -a "Raycast"'  # Raycast
    alt-ctrl-z = 'exec-and-forget open -a "Zoom"'  # zoom.us

    # Terminal-hosted tools keep their Linux letters but launch a kitty window
    # directly rather than going through the btop-gui/yazi-gui/notetaker wrappers,
    # which are Hyprland-specific.
    alt-ctrl-b = 'exec-and-forget open -na kitty --args --title btop -e btop'
    alt-ctrl-f = 'exec-and-forget open -na kitty --args --title yazi -e yazi'
    alt-ctrl-n = 'exec-and-forget open -na kitty --args --title notetaker -e nvim /Users/matth/Obsidian/Main'

    # ── modes ──────────────────────────────────────────────────────────────────
    alt-shift-space = 'mode leader'
    alt-g = 'mode translate'
    alt-shift-g = 'mode translate-alt'

    [mode.leader.binding]
    # N-minute timer, the SUPER+SHIFT+SPACE leader submap from Hyprland.
    1 = ['exec-and-forget leader-timer 1', 'mode main']
    2 = ['exec-and-forget leader-timer 2', 'mode main']
    3 = ['exec-and-forget leader-timer 3', 'mode main']
    4 = ['exec-and-forget leader-timer 4', 'mode main']
    5 = ['exec-and-forget leader-timer 5', 'mode main']
    6 = ['exec-and-forget leader-timer 6', 'mode main']
    7 = ['exec-and-forget leader-timer 7', 'mode main']
    8 = ['exec-and-forget leader-timer 8', 'mode main']
    9 = ['exec-and-forget leader-timer 9', 'mode main']
    0 = ['exec-and-forget leader-timer 10', 'mode main']
    esc = 'mode main'

    [mode.translate.binding]
    # Raycast's Translate extension replaces the dialect/crow-translate popups.
    enter = ['exec-and-forget open -g "raycast://extensions/raycast/translator/translate"', 'mode main']
    esc = 'mode main'

    [mode.translate-alt.binding]
    enter = ['exec-and-forget open -g "raycast://extensions/raycast/translator/translate?fallbackText="', 'mode main']
    esc = 'mode main'
  '';
}
