keys:
  - &user_matth age1gymgx3qqady7vwtg28ng7huug783qnttvpezu4cdrezh356esfhqzcp04m
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *user_matth
